BEGIN TRANSACTION;
CREATE TABLE users (
  userId serial PRIMARY KEY,
  name VARCHAR(100),
  email text UNIQUE NOT NULL,
  hash VARCHAR(128) NOT NULL,
  token VARCHAR,
  joined TIMESTAMP NOT NULL
);
COMMIT;